# .github/workflows/fetch_jobs.yml
name: Fetch Remote Software Jobs

on:
  workflow_dispatch: # Allows manual triggering from any branch
  push:
    branches: [ main, feature/test ] # Runs on pushes to main or feature/test

  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours

jobs:
  fetch-and-update-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Fetch job data and update database
        env:
          # Required API key for Google Search
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
          SERPER_API_KEY2: ${{ secrets.SERPER_API_KEY2 }}
          SERPER_API_KEY3: ${{ secrets.SERPER_API_KEY3 }}

          # Required database credentials
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

          # Optional: Override default DB connection info if needed
          # DB_HOST: ${{ secrets.DB_HOST }}
          # DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          python scripts/fetch_jobs.py
